<?php
/**
 * CapsFilterPostModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SayWhenTimeSlotCaps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SayWhen TimeSlot Caps for Nachon
 *
 * SayWhen TimeSlot Caps for Nachon API Documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SayWhenTimeSlotCaps;

/**
 * CapsFilterPostModelTest Class Doc Comment
 *
 * @category    Class */
// * @description CapsFilterPostModel
/**
 * @package     SayWhenTimeSlotCaps
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CapsFilterPostModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CapsFilterPostModel"
     */
    public function testCapsFilterPostModel()
    {
    }

    /**
     * Test attribute "time_slots"
     */
    public function testPropertyTimeSlots()
    {
    }

    /**
     * Test attribute "bop_id"
     */
    public function testPropertyBopId()
    {
    }
}
