<?php
/**
 * RegisterAppointmentPostModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SayWhenTimeSlotCaps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SayWhen TimeSlot Caps for Nachon
 *
 * SayWhen TimeSlot Caps for Nachon API Documentation
 *
 * OpenAPI spec version: 1.1
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SayWhenTimeSlotCaps;

/**
 * RegisterAppointmentPostModelTest Class Doc Comment
 *
 * @category    Class */
// * @description RegisterAppointmentPostModel
/**
 * @package     SayWhenTimeSlotCaps
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RegisterAppointmentPostModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RegisterAppointmentPostModel"
     */
    public function testRegisterAppointmentPostModel()
    {
    }

    /**
     * Test attribute "fop_id"
     */
    public function testPropertyFopId()
    {
    }

    /**
     * Test attribute "visit_type"
     */
    public function testPropertyVisitType()
    {
    }

    /**
     * Test attribute "date_timefrom"
     */
    public function testPropertyDateTimefrom()
    {
    }

    /**
     * Test attribute "date_time_to"
     */
    public function testPropertyDateTimeTo()
    {
    }
}
