<?php
/**
 * FilterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SayWhenTimeSlotCaps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SayWhen TimeSlot Caps for Nachon
 *
 * SayWhen TimeSlot Caps for Nachon API Documentation
 *
 * OpenAPI spec version: 1.1
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SayWhenTimeSlotCaps;

use \SayWhenTimeSlotCaps\Configuration;
use \SayWhenTimeSlotCaps\ApiClient;
use \SayWhenTimeSlotCaps\ApiException;
use \SayWhenTimeSlotCaps\ObjectSerializer;

/**
 * FilterApiTest Class Doc Comment
 *
 * @category Class
 * @package  SayWhenTimeSlotCaps
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FilterApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for filterTimeSlotCaps
     *
     * Filter TimeSlots for Caps.
     *
     */
    public function testFilterTimeSlotCaps()
    {
    }
}
